### ISSUE TITLE
Add page with aggregated links to all projects docs for release train current release

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-release-tools#113]
We currently have docs per project per release: https://spring.io/projects/spring-cloud-netflix#learn so actually it might be tricky for the user to find the right version of the docs for their release train straightaway; It would be better to aggregate it somewhere in one site with all doc links per release train

**Comment by snicoll** [comment]
I am not 100% sure this would fit our purpose. Consider the use case where you want to link to a given section of the doc and all you have is the release train (which is what most users would have AFAIK):

Let's take an example: https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.2.RELEASE/single/spring-cloud-netflix.html#_eureka_s_health_checks

Concretely, I'd like to be able to specify somewhere in the URL the version of the release train, rather than having the version of the component. We've made a good job with the BOM to make that information not important to the user so it would be nice if we could get that done at doc level as well.

Having a centralized page is a very good step in the right direction but won't help us for the original use case of adding links to the initializr (as we'd still have to translate the release train to some module version).

**Comment by spencergibb** [comment]
We already have docs aggregated for the whole release train

**Comment by ryanjbaxter** [comment]
https://cloud.spring.io/spring-cloud-static/Finchley.SR2/

**Comment by snicoll** [comment]
Is there such initiative for `Greenwich`?

**Comment by ryanjbaxter** [comment]
Hmmm looks like its not published, we can take care of that though next week

**Comment by ryanjbaxter** [comment]
@snicoll i just published the docs https://cloud.spring.io/spring-cloud-static/Greenwich.M3/

Is that what you were looking for?

**Comment by snicoll** [comment]
Thanks for the feedback. I am looking for the Google GCP documentation. Is that supposed to be there?

**Comment by artembilan** [comment]
Thanks @snicoll , for raising this concern!

I also have such a concern in my back log to come back one to @ryanjbaxter to work out the solution to join Spring Cloud GCP docs to the standard Spring Cloud release train.

What should we do from the Spring Cloud GCP perspective to normalize its docs?

Another question is to rework Spring Cloud GCP project page to the Spring Cloud style: https://cloud.spring.io/spring-cloud-gcp/
Any insights on the matter?

Thanks

**Comment by ryanjbaxter** [comment]
@snicoll you are right it is not included and it should be

@artembilan I took a quick look at the GCP docs.  It doesnt look like you are following all of our conventions when it comes to the documentation.  For example, the documentation module is usually just named `docs` in all of our projects.  Also the documentation is generated when the `docs` profile is activates where as in GCP its generated when `full` is activated.  I think we should address this and then we can get the GCP docs incorporated in the release train docs.  Do you want to create an issue in GCP to track this?

As far as the project page is concerned you should be able to transition that over to the new project page style by filling out the content here https://spring.io/admin/projects/spring-cloud-gcp.  Then editing `index.html` in your `gh-pages` branch to redirect to http://spring.io/projects/spring-cloud-gcp (see https://github.com/spring-cloud/spring-cloud-netflix/blob/gh-pages/index.html)

Anyone object to closing this issue then?

**Comment by artembilan** [comment]
Sounds good, @ryanjbaxter !

Raising an issue in SC GCP project...

**Comment by OlgaMaciaszek** [comment]
Already covered in #108

**Comment by artembilan** [comment]
@ryanjbaxter , I think I did everything right for the Spring Cloud GCP project page: https://spring.io/projects/spring-cloud-gcp

And it also redirects well from the umbrella Spring Cloud project page.

Thank you for your guidance!

/CC @meltsufin
